# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Eric's STAT110 Journey"

# URL
baseurl:            "//ebailey78.github.io/STAT110/"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "STAT110 Site"
    href:           "//projects.iq.harvard.edu/stat110"
  - name:           "Nathan's Blog"
    href:           "//natebyers.github.io/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
